services:
  db:
    image: mysql:8.4
    container_name: andrian_irmawan_101032300219_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_clo2_demo
      MYSQL_DATABASE: clo2_comments
      MYSQL_USER: clo2_user
      MYSQL_PASSWORD: clo2_pass
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -proot_clo2_demo --silent"]
      interval: 10s
      timeout: 5s
      retries: 8
    networks:
      clo2_net:
        ipv4_address: 192.168.219.220

  web:
    build:
      context: .
      dockerfile: docker/php-apache/Dockerfile
    container_name: andrian_irmawan_101032300219_web
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_NAME: clo2_comments
      DB_USER: clo2_user
      DB_PASS: clo2_pass
      LOGIN_MODE: vulnerable
      EXTERNAL_HTTPS_PORT: ${HTTPS_PORT:-8443}
    ports:
      - "${HTTP_PORT:-8080}:80"
      - "${HTTPS_PORT:-8443}:443"
    networks:
      clo2_net:
        ipv4_address: 192.168.219.219

volumes:
  db_data:

networks:
  clo2_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.219.0/24
